Add share component
infinum/eightshift-frontend-libs pull request #210
Opened 2020-12-17 16:27 UTC by gabriel-glo

Share component lists 4 networks that support share links.

On mobile devices should open a native share dialog.

I didn't figure out how to control the display of certain social networks in  component options, so feedback is welcome on that side.

2020-12-17 16:33 UTC, iruzevic requested changes

2020-12-17 16:33 UTC, iruzevic commented on blocks/init/src/Blocks/components/share/share.php
> +	Components::selector($componentClass, $componentClass, 'item',),
you have a rouge comma here

2020-12-17 16:33 UTC, iruzevic commented on blocks/init/src/Blocks/components/share/share.php
> +	Components::selector($blockClass, $blockClass, 'item',),
you have a rouge comma here

2020-12-17 16:33 UTC, iruzevic commented on blocks/init/src/Blocks/components/share/share.php
> +	Components::selector($blockClass, $blockClass, "{$selectorClass}"),
no need for template string here

2020-12-17 16:33 UTC, iruzevic commented on blocks/init/src/Blocks/components/share/share.php
> +$postUrl = \get_the_permalink();
this options should be passed as a props an not defined fixed here. 
If for some reason you want to use this component outside of posts this wont work. Please add all of the options via props, you can defined this values as fallback if nothing is passed

2020-12-18 10:31 UTC, iruzevic approved these changes

2020-12-18 12:04 UTC, dingo-d approved these changes

2020-12-18 14:55 UTC, IvanGrginovInf approved these changes

2020-12-21 09:19 UTC, kmaric69 approved these changes

2020-12-21 10:07 UTC, merged