Custom select async option
infinum/eightshift-frontend-libs pull request #322
Opened 2021-04-21 14:47 UTC by goranalkovic-infinum

Allows Custom select to have asynchronously loaded options via a callback function.
More info in the Storybook readme and stories.

2021-04-21 15:07 UTC, IvanGrginovInf submitted a review, later dismissed

2021-04-22 06:34 UTC, dingo-d requested changes
Left a few comments, awesome job!

2021-04-22 06:34 UTC, dingo-d commented on scripts/components/custom-select/docs/readme.mdx
> +As this control can be used as a synchronous (options passed to component) or an asynchronous (options loaded via callback) component,
```suggestion
This control can be used as a synchronous (options passed to component) or an asynchronous (options loaded via callback) component,
```

2021-04-22 06:34 UTC, dingo-d commented on scripts/components/custom-select/docs/readme.mdx
> +| `isSearchable` | _(optional)_ If `true` allows searching through results. Default: `true`. |
```suggestion
| `isSearchable` | _(optional)_ If `true` allows searching through the results. Default: `true`. |
```

2021-04-22 08:00 UTC, dingo-d approved these changes

2021-04-22 08:06 UTC, dingo-d approved these changes

2021-04-22 09:51 UTC, IvanGrginovInf approved these changes

2021-04-22 09:51 UTC, merged