updating variables
infinum/eightshift-frontend-libs pull request #340
Opened 2021-05-17 22:15 UTC by iruzevic

2021-05-18 08:16 UTC, dingo-d commented on blocks/init/src/Blocks/components/image/components/image-options.js
> +									{__('Image Url', 'Redesign')}
```suggestion
									{__('Image Url', 'eightshift-frontend-libs')}
```

2021-05-18 08:17 UTC, dingo-d commented on blocks/init/src/Blocks/components/image/components/image-options.js
> +										label={sprintf(__('Image %s screen size', 'Redesign'), pointLabel)}
```suggestion
										label={sprintf(__('Image %s screen size', 'eightshift-frontend-libs'), pointLabel)}
```

2021-05-18 08:27 UTC, dingo-d commented on blocks/init/src/Blocks/components/image/components/image-options.js
> +													{sprintf(__('Remove %s screen size image', 'Redesign'), pointLabel)}
```suggestion
													{sprintf(__('Remove %s screen size image', 'eightshift-frontend-libs'), pointLabel)}
```

2021-05-18 08:29 UTC, dingo-d requested changes
Some minor copy/paste typos

2021-05-18 09:17 UTC, dingo-d approved these changes

2021-05-18 09:32 UTC, volfkarlo approved these changes
Awesome job, so happy about these changes!

2021-05-19 19:32 UTC, iruzevic commented on blocks/init/src/Blocks/assets/styles/editor/_editor.scss
> +	font-size: var(--base-font-size);
I will need to test it

2021-05-19 19:33 UTC, iruzevic commented on blocks/init/src/Blocks/components/accordion/accordion-style.scss
> +	--accordion-scoped-icon-size: 1.5em;
I will test this and check

2021-05-19 19:35 UTC, iruzevic commented on blocks/init/src/Blocks/components/loader/loader-style.scss
> +			border-top-color: var(--loader-scoped-item-1-color);
there is really no need for the fallback. It is scoped variable that implements the global color. If the global color is not there it the fallback will also fail

2021-05-19 19:35 UTC, merged

2021-05-19 19:36 UTC, iruzevic commented
I will check all the issues here and fix them in the next PR