Feature/updates
infinum/eightshift-frontend-libs pull request #400
Opened 2021-07-19 16:23 UTC by iruzevic

- updating component and blocks
You can run PR via commits

2021-07-19 17:35 UTC, dingo-d commented on blocks/init/src/Blocks/custom/carousel/docs/readme.mdx
> +npm audit fix
Wrong copy paste? 😄

2021-07-19 17:36 UTC, dingo-d requested changes
One small comment about documentation otherwise looks good 👍🏼

2021-07-20 05:56 UTC, iruzevic commented on blocks/init/src/Blocks/custom/carousel/docs/readme.mdx
> +npm audit fix
jap :D

2021-07-20 05:57 UTC, iruzevic commented on blocks/init/src/Blocks/custom/carousel/docs/readme.mdx
> +npm audit fix
fixed

2021-07-20 07:09 UTC, goranalkovic-infinum approved these changes

2021-07-20 07:42 UTC, gabriel-glo requested changes
Just a few comments

2021-07-20 07:42 UTC, gabriel-glo commented on blocks/init/src/Blocks/custom/carousel/docs/readme.mdx
> +How ever we prefere to use Swiper as our carousel of choice.
```suggestion
However, we prefer to use Swiper as our carousel of choice.
```

2021-07-20 07:42 UTC, gabriel-glo commented on scripts/components/link-toolbar-button/link-toolbar-button.js
> +			[`${onChangeUrl}`]: undefined,
Is this string literal really needed?

2021-07-20 08:20 UTC, dingo-d approved these changes

2021-07-20 08:21 UTC, IvanGrginovInf approved these changes

2021-07-20 10:10 UTC, IvanGrginovInf approved these changes
Apart from what @gabriel-glo commented it looks good

2021-07-20 11:26 UTC, volfkarlo requested changes
Just a question :) 

Great job! 😄

2021-07-21 16:24 UTC, iruzevic commented on blocks/init/src/Blocks/components/button/components/button-toolbar.js
> +							onChangeIsNewTab={getAttrKey('buttonIsNewTab', attributes, manifest)}
jes I think Goran described this in the previous comment

2021-07-21 16:27 UTC, merged