updating helpers docs
infinum/eightshift-frontend-libs pull request #415
Opened 2021-07-30 08:32 UTC by iruzevic

- documentation for all scripts and removing the script exports that are not used and should not be used by the users.
- adding usage and output examples so we can have documentation in one place.

In combination with this PR on docs

2021-07-30 09:19 UTC, dingo-d commented on scripts/editor/get-actions.js
> + * This helper is deprecated and should not be used anymore.
Maybe we can use https://jsdoc.app/tags-deprecated.html for this?

2021-07-30 09:22 UTC, dingo-d commented on scripts/plugins/yoast-seo.js
> + * This helper will search all blocks and components manifests and find attributes that have "seo": "true" key.
```suggestion
 * This helper will search all blocks and component manifests and find attributes that have "seo": "true" key.
```

2021-07-30 09:25 UTC, dingo-d requested changes
Left some minor comments

2021-08-12 12:29 UTC, goranalkovic-infinum requested changes
Left some suggestions

2021-08-12 12:29 UTC, goranalkovic-infinum commented on scripts/editor/get-actions.js
> + * @deprecated We stopped using getActions helper and covered to the native way of writing setAttributes
```suggestion
 * @deprecated This helper is not used anymore. Write regular `setAttributes` instead.
```

2021-08-12 12:29 UTC, goranalkovic-infinum commented on scripts/editor/get-actions.js
> + * This helper is deprecated and should not be used anymore.
```suggestion
 * _This helper is deprecated and should not be used anymore._
```

2021-08-12 12:29 UTC, goranalkovic-infinum commented on scripts/editor/get-options.js
> + * This function is deprecated and getOption should be used.
```suggestion
 * _This function is deprecated._
 *
 * @deprecated Use `getOption` instead.
```

2021-08-12 12:29 UTC, goranalkovic-infinum commented on scripts/editor/output-css-variables.js
> + * Returns a unique ID generally used for css variables.
```suggestion
 * Returns a unique ID, generally used with CSS variable generation.
```

2021-08-12 12:29 UTC, goranalkovic-infinum commented on scripts/editor/override-inner-block-attributes.js
> + * Used to set attributes on all innerBlocks. This value will be stored in the block editor store and set to a block.
```suggestion
 * Sets attributes on all `innerBlocks`. This value will be stored in the Block editor store and set to a block.
```

2021-08-12 12:29 UTC, goranalkovic-infinum commented on scripts/editor/override-inner-block-attributes.js
> + * Used to set attributes on all innerBlocks preset only for simple wrapper setup. This value will be stored in the block editor store and set to a block.
```suggestion
 * Sets attributes on all `innerBlocks`, with Simple wrapper options preset. This value will be stored in the Block editor store and set to a block.
```

2021-08-12 12:29 UTC, goranalkovic-infinum commented on scripts/helpers/escape-string.js
> + * ```js
```suggestion
 * ```
```

2021-08-12 12:29 UTC, goranalkovic-infinum commented on scripts/plugins/yoast-seo.js
> + * This helper will search all blocks and component manifests and find attributes that have "seo": "true" key.
```suggestion
 * Searches all blocks and component manifests and returns attributes that have `"seo": "true"` set.
```

2021-08-12 12:32 UTC, dingo-d submitted a review, later dismissed

2021-08-12 12:37 UTC, goranalkovic-infinum approved these changes

2021-08-12 13:04 UTC, dingo-d approved these changes

2021-08-12 13:23 UTC, volfkarlo submitted a review, later dismissed

2021-08-12 14:21 UTC, mbmjertan requested changes

2021-08-12 14:21 UTC, mbmjertan commented on scripts/helpers/cookies.js
> + * Helper to set and unset cookies.
Perhaps listing the available helper methods for time (`setOneDay` etc.) would be useful.

2021-08-12 14:21 UTC, mbmjertan commented on scripts/helpers/text-helpers.js
> + * @returns {string}
```suggestion
 * @returns {string} Truncated string.
```

2021-08-12 14:26 UTC, iruzevic commented on scripts/helpers/text-helpers.js
> + * Slices the string and inputs the provided separator after the specified characters.
Please create a issue for this @mbmjertan

2021-08-12 14:26 UTC, merged