Fix Yoast analysis
infinum/eightshift-frontend-libs pull request #501
Opened 2021-11-22 19:54 UTC by dingo-d

Improves the regex for capturing content from the attributes. 

I added a way to include image URLs so those are also included in the analysis (when `seo` is added in the image component). 

We should see how to add image `alt` since Yoast probably analyses this as well. I also replaced the unicode characters with their non-unicode counterparts, since that prevented Yoast from detecting outbound and internal links. This was tested on the Yoast Pro version. 

The last thing that probably should get improved is ordering the content because I think this just parses blocks in some weird order. And headings are not wrapped in correct h tags which also skews the analysis.

Partially fixes #485 

This needs to be fixed:

<img width="212" alt="image" src="https://user-images.githubusercontent.com/8638515/142926017-8f368fe0-9950-4211-a567-0778e48f89ff.png">

This is now fixed:

<img width="223" alt="image" src="https://user-images.githubusercontent.com/8638515/142926062-602326b6-420f-4b36-9be9-f93ea2b79528.png">

Before it was like this: 

<img width="230" alt="image" src="https://user-images.githubusercontent.com/8638515/142926259-39eebe7e-e41f-445c-bb61-08d6b2d1d84f.png">

2021-11-22 23:51 UTC, iruzevic submitted a review, later dismissed

2021-11-23 07:20 UTC, dingo-d commented
Still need to write tests for this. I'd like to transform our blocks to proper HTML, in order to have a better analysis.

2021-11-23 13:35 UTC, dadadavorin submitted a review, later dismissed

2021-11-24 07:40 UTC, iruzevic submitted a review, later dismissed

2021-11-24 09:54 UTC, gabriel-glo reviewed
Small fix on function arguments.

2021-11-24 09:54 UTC, gabriel-glo commented on scripts/plugins/yoast-seo.js
> +		YoastSEO.app.registerPlugin( 'YoastSEOCustomData', { status: 'ready' } );
```suggestion
		YoastSEO.app.registerPlugin('YoastSEOCustomData', {status: 'ready'});
```

2021-11-24 09:59 UTC, goranalkovic-infinum approved these changes
Approve, but fix the indents Gabriel suggested pls

2021-11-24 10:40 UTC, dingo-d commented
I still need to add the tests and the proper HTML parser/serializer. Because there isn't a built-in HTML serializer from the core.

2021-11-29 06:49 UTC, volfkarlo requested changes

2021-11-29 06:49 UTC, volfkarlo commented on scripts/plugins/yoast-seo.js
> +
```suggestion

```

2022-01-19 12:42 UTC, dingo-d commented
@infinum/wordpress-team anybody willing to take this over? The parser just needs to be added that will chew the content and return HTML (there are automated tests that will help).

2022-01-19 13:29 UTC, iruzevic commented
I will make this work

2022-03-28 09:36 UTC, iruzevic commented
closing the PR due to different approach.

2022-03-28 09:36 UTC, closed without merging