Change color scheme to match WCAG contrast requirements
infinum/eightshift-frontend-libs pull request #559
Opened 2022-02-08 14:33 UTC by mbmjertan

# Description

This PR changes the default color scheme so the contrast with white or black foregrounds is in line with WCAG AAA requirements (as they're mostly used as background colors for white or black text, mostly on buttons and as wrapper backgrounds).

As this is WCAG AAA compliant, lesser contrast (which will probably happen if the foreground colors aren't exactly `#fff` or `#000`) should still be AA-level compliant.

As project usually define their own color schemes, this PR will only affect the starter theme. As discussed previously with @iruzevic, these colors don't have brand meaning and were chosen arbitrarily, so these changes are mostly the same.

I'll work on a contrast warning later on.

# Screenshots / Videos
This is what buttons now look like:
<img width="216" alt="Screenshot 2022-02-08 at 15 28 56" src="https://user-images.githubusercontent.com/1742806/153007846-434721b5-cb15-4bca-9766-968794c06cea.png">

# Linked documentation PR

Relevant: https://webaim.org/resources/contrastchecker/

2022-02-08 14:39 UTC, iobrado submitted a review, later dismissed

2022-02-08 15:25 UTC, gabriel-glo approved these changes

2022-02-08 15:31 UTC, goranalkovic-infinum requested changes
While the current colors aren't any official brand colors, they represented all the color of Eightshift and its projects 😄 

But to be fully a11y compliant, here are some new colors that are fully WCAG AAA compliant. (Some of the current colors like yellow were compared to a white foreground, there was never a chance they would be WCAG AAA compliant 😄 , the ones that need a black foreground to be compliant are highlighted in change requests).

Also, here are new values for:
- `mist`: `#F1FBFE`
- `dew`: `#FAF8FC`
- `cream`: `#FFFBF5`

Here's a preview:
![image](https://user-images.githubusercontent.com/77000136/153019956-2129a9d6-0e25-484f-a6e9-4bbc6c80de54.png)

2022-02-08 15:31 UTC, goranalkovic-infinum commented on blocks/init/src/Blocks/manifest.json
> +				"color": "#77460D"
```suggestion
				"color": "#FFEA00"
```
Needs to have black text for WCAG AAA.

2022-02-08 15:31 UTC, goranalkovic-infinum commented on blocks/init/src/Blocks/manifest.json
> +				"color": "#AF1818"
```suggestion
				"color": "#B30024"
```

2022-02-08 15:31 UTC, goranalkovic-infinum commented on blocks/init/src/Blocks/manifest.json
> +				"color": "#155D7E"
```suggestion
				"color": "#00B8D4"
```
Needs to have black text for WCAG AAA.

2022-02-08 15:38 UTC, mbmjertan commented on blocks/init/src/Blocks/manifest.json
> +				"color": "#662ED6"
Isn't this #6F2ADE on the screenshot?

2022-02-08 15:38 UTC, goranalkovic-infinum commented on blocks/init/src/Blocks/manifest.json
> +				"color": "#662ED6"
Good catch, should be #662ED6

2022-02-09 09:52 UTC, mbmjertan commented
Changes suggested by @goranalkovic-infinum have been added, and I've went ahead and set some different defaults for link colors and their hover states in paragraphs and lists for contrast improvements.

2022-02-09 10:01 UTC, goranalkovic-infinum approved these changes

2022-02-09 10:30 UTC, dingo-d approved these changes

2022-02-09 11:54 UTC, merged