Fixes for Quote block/component a11y
infinum/eightshift-frontend-libs pull request #574
Opened 2022-03-02 14:50 UTC by mbmjertan

# Description

The `quote` component currently renders the quote content as a `heading`. 

This is problematic as the `heading` component always outputs an `h1-h6` element, and assistive technologies allow users to navigate the page using them. Using headings for quotes (and other non-heading content) poisons our accessibility tree.

To fix this, I've replaced the use of the `heading` component with the `paragraph` component inside the `quote` component. However, to make sure that this component switcheroo isn't a breaking change, I've kept the `heading` prefix for quote content. 

Also, to make sure that quotes don't look too different from what they've looked like before, and so that configuration attributes aren't lost, I've added the options we have for `headingSize` to the `paragraph` component as well. The styles and sizes for them aren't a 1-to-1 match (because existing options already differ), but all options exists so that they don't get overridden if someone updates to this component version. 

To improve the user experience a bit, I've also added some labels and switches to `ParagraphOptions` in `QuoteOptions`.

# Screenshots / Videos

Look, ma, I'm a `<p>`.
![Screenshot 2022-03-02 at 15 48 56](https://user-images.githubusercontent.com/1742806/156385083-ef59a807-0e48-4745-a901-8328dc3fbbd9.png)

Who turned off the attribution?
![Screenshot 2022-03-02 at 15 48 24](https://user-images.githubusercontent.com/1742806/156385164-343be531-d1b4-49d7-a7f8-cbbca7a20d70.png)

2022-03-02 14:58 UTC, iobrado requested changes
I've noticed one wrong textdomain 🙂

2022-03-02 14:58 UTC, iobrado commented on blocks/init/src/Blocks/components/quote/components/quote-options.js
> +						label={__('Attribution', 'access-guru')}
```suggestion
						label={__('Attribution', 'eightshift-frontend-libs')}
```

2022-03-02 15:06 UTC, iobrado approved these changes

2022-03-02 15:53 UTC, dingo-d approved these changes

2022-03-03 08:23 UTC, dadadavorin approved these changes

2022-03-03 09:39 UTC, merged