updating css variables
infinum/eightshift-frontend-libs pull request #600
Opened 2022-04-01 08:29 UTC by iruzevic

# Description

- updating css variables and inline logic to use our internal store for storing data.

2022-04-01 08:34 UTC, gabriel-glo approved these changes

2022-04-01 08:36 UTC, goranalkovic-infinum requested changes
2 very minor comments, awesome job!

2022-04-01 08:36 UTC, goranalkovic-infinum commented on scripts/editor/output-css-variables.js
> + * Return css variables in default type. On the place where it was called.
```suggestion
 * Return CSS variables in default type. On the place where it was called.
```

2022-04-01 08:36 UTC, goranalkovic-infinum commented on scripts/editor/output-css-variables.js
> + * Output css variables as a one inline style tag.
```suggestion
 * Output CSS variables as a one inline style tag.
```

2022-04-01 08:37 UTC, simun-ivanac submitted a review, later dismissed

2022-04-01 08:41 UTC, dadadavorin submitted a review, later dismissed
Nice 👍

2022-04-01 08:44 UTC, goranalkovic-infinum submitted a review, later dismissed

2022-04-01 08:44 UTC, iobrado submitted a review, later dismissed

2022-04-01 09:11 UTC, mbmjertan submitted a review, later dismissed

2022-04-01 10:20 UTC, dingo-d submitted a review, later dismissed

2022-04-01 12:47 UTC, volfkarlo submitted a review, later dismissed
👏  Application-like things! Awesome! 😄

2022-04-01 13:34 UTC, dadadavorin submitted a review, later dismissed

2022-04-04 11:53 UTC, iobrado approved these changes

2022-04-06 10:17 UTC, goranalkovic-infinum requested changes
1 more ultra-minor thing 😄

2022-04-06 10:17 UTC, goranalkovic-infinum commented on scripts/editor/options.js
> +import { getPaletteColors } from "./colors";
```suggestion
import { getPaletteColors } from './colors';
```
for consistency 😄

2022-04-08 09:09 UTC, iobrado approved these changes

2022-04-13 15:34 UTC, dadadavorin approved these changes

2022-04-14 06:33 UTC, dingo-d submitted a review, later dismissed

2022-04-19 08:40 UTC, volfkarlo approved these changes
Awesome stuff!

2022-04-19 20:05 UTC, merged