Fix a bug in Safari for hamburger animations
infinum/eightshift-frontend-libs pull request #622
Opened 2022-05-23 14:36 UTC by piqusy

# Description

Fix a bug in Safari which causes a glitch in hamburger from default to active state (`is-menu-open`) animation.

# Screenshots / Videos

This is how it looks like in Safari and iOS without the fix:
https://user-images.githubusercontent.com/22823970/169843183-a9275d77-5996-48e1-9fff-9828c43605eb.mov

2022-05-23 14:47 UTC, mbmjertan approved these changes

2022-05-23 14:56 UTC, volfkarlo requested changes

2022-05-23 15:02 UTC, piqusy commented on blocks/init/src/Blocks/components/hamburger/hamburger-style.scss
> +				transform: rotate(45deg) translate3d(0, 20%, 0) scale3d(1, 1, 1);
Yes, it is a part of the hover animation. The same glitch is present if not for these.

2022-05-23 15:58 UTC, volfkarlo commented on blocks/init/src/Blocks/components/hamburger/hamburger-style.scss
> +				transform: rotate(45deg) translate3d(0, 20%, 0) scale3d(1, 1, 1);
Thanks for the info 😄

2022-05-23 15:58 UTC, volfkarlo approved these changes

2022-05-24 06:37 UTC, piqusy commented on blocks/init/src/Blocks/components/hamburger/hamburger-style.scss
> +				transform: rotate(45deg) translate3d(0, 20%, 0) scale3d(1, 1, 1);
No problem, thank you for reviewing 😌

2022-05-24 06:37 UTC, merged