Goc's summer goodie bag #1
infinum/eightshift-frontend-libs pull request #661
Opened 2022-08-29 18:30 UTC by goranalkovic-infinum

Changes:

# Component updates

## `ComponentUseToggle`
Just because it's rarely used, doesn't mean it had to still look old! It's been updated to match the `CollapsableComponentUseToggle` styling.

<img width="279" alt="image" src="https://user-images.githubusercontent.com/77000136/187266328-cee07373-4118-44cf-be8d-b24d6bc6bb16.png">

The separator line is still here:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/77000136/187266440-be3b6542-1e5e-4d7f-a455-0eefcfb6ab82.png">

## `ColorPaletteCustom`
Slightly increased color tile size to easily spot differences in the shades.

<img width="268" alt="image" src="https://user-images.githubusercontent.com/77000136/187260303-331a477d-8e5d-4e04-a448-434df77d5711.png">

## `CollapsableComponentUseToggle` / `Collapsable`
Reduced number of colors in expanded state to reduce visual clutter.

The chevron now changes to a filled icon when expanded to signify the open state.

Toggle icon is now slightly smaller so the control better aligns with other options. To make it easier to spot, it uses a slightly different off state now.

![image](https://user-images.githubusercontent.com/77000136/187262126-a37ff7b7-8ca1-42ce-bfe0-f8413ef7ade9.png)

Both toggle and the chevron have a fun new animation.

https://user-images.githubusercontent.com/77000136/187260990-1a58c72c-fba3-4ac2-8ab1-549da2899593.mov

## `CompactResponsive`
To make it a bit less confusing, the _Inherit_ options looks totally different now! All the code behind stayed the same.

https://user-images.githubusercontent.com/77000136/187262583-50c98553-7292-4bf4-bb3f-5a4f466050b9.mov

## `CustomSelect`
There's a new, more compact caret icon.
<img width="126" alt="image" src="https://user-images.githubusercontent.com/77000136/187262805-d55952f8-98f1-438f-b856-2332fca40ba3.png">

Now, if you don't pass `label` and `help`, the component will just render itself, without the extra `BaseControl`.

## `MatrixAlignControl`
Apparently, somewhere between WP 5.9 and 6.x, a new control was added (`AlignmentMatrixControl`) to replace the other 2 existing matrix align controls.

Everything still works seamlessly and will fall back to older controls if they're not available.

## Color reductions (ft. `FancyDivider` and `CustomSlider`)
Inflation is getting crazy and color is getting expensive, we had to do something about it...
just kidding!

To reduce visual clutter, the default icons now use a neutral blueish gray instead of the accent color.
<img width="279" alt="image" src="https://user-images.githubusercontent.com/77000136/187263458-0feb88f6-3936-47ae-8ce9-e41d0b13dc1e.png">

Also, `FancyDivider` and `CustomSlider` had their default color tweaked very slightly.

## `IconToggle`
This little control started as a simple wrapper around the default Gutenberg toggle to allow it to have an icon. After graduating to a checkbox option recently, now it's getting a major upgrade!

The little `IconToggle` is now a toggling powerhouse! The new `type` parameter allows you to pick from **5** available designs!

1) The classic - `toggle`

<img width="279" alt="image" src="https://user-images.githubusercontent.com/77000136/187265021-7be96424-8447-4689-97d4-b4d32b72dd94.png">

2) The even more classic - `checkbox`
<img width="278" alt="image" src="https://user-images.githubusercontent.com/77000136/187265053-1ba5ae60-60d3-407f-8959-f45629a71a8f.png">

3) Fancy, yet basic - `button`

<img width="270" alt="image" src="https://user-images.githubusercontent.com/77000136/187265195-5e5e5841-9636-476e-bbed-5fd8f518e164.png">

4) Minimal, but powerful - `iconButton` (tooltip included!)

<img width="104" alt="image" src="https://user-images.githubusercontent.com/77000136/187265168-fa0b7b68-2e69-4364-adf1-7df38de92793.png">

5) Modern & compact - `tileButton`

<img width="185" alt="image" src="https://user-images.githubusercontent.com/77000136/187265088-d04ff9e5-3ae3-4f3d-801c-01e38145b1ab.png">

Don't worry, the default is still the classic toggle :)

Also, they all share the same options, so feel free to... toggle them... as you wish!

## `SimpleHorizontalSingleSelect`
Updated the styling of the active state to give icons more contrast and make it look a bit nicer :)

<img width="276" alt="image" src="https://user-images.githubusercontent.com/77000136/187265496-29645cb9-20bf-4bca-b665-7e55623a816e.png">

<img width="260" alt="image" src="https://user-images.githubusercontent.com/77000136/187265616-28bf1141-3f2c-4668-93fa-d5d80ad1335c.png">

## `LinkEditComponent`
This little fellow took over it's toolbar sibling's job recently, and has been doing fine ever since.

Now it had a slight redesign in it's default form and a couple of new functionalities.

In the default state it's all clickable now, compared to the little button on the side.

<img width="267" alt="image" src="https://user-images.githubusercontent.com/77000136/187271764-1037d531-709b-48ca-8993-075b5602af53.png">

After adding a link you still get a little preview and the edit icon to make you want to change the URL and the options.

<img width="264" alt="image" src="https://user-images.githubusercontent.com/77000136/187271888-6f32c13a-d347-4fcf-ac0a-7f00e4fdccd1.png">

The open state is a bit more compact and nicer looking now, with all the basics still there.

<img width="472" alt="image" src="https://user-images.githubusercontent.com/77000136/187272125-9bb75bb4-7efa-4589-9612-eb25b42f6f8b.png">

A little easter egg that ties into a new feature, if you add an anchor link, there' s a new indicator and a short message to remind you what it is.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/77000136/187272252-8de5cc16-d17e-4220-bc76-a547aaf3a9ce.png">

Also, if you provided the attribute name for it, the component can now auto-set the `isAnchor` parameter when you enter an anchor link, no more manual clicks!

All the other view modes and functionalities like space for extra controls are still here!

## `IconLabel`
This makes most of the admin look nice(r) and has saved a lot of lines of code since it was introduced \*

Now it has a `subtitle` parameter to add short descriptions for your main label if needed.

<img width="240" alt="image" src="https://user-images.githubusercontent.com/77000136/187265881-4735a63f-7b7e-4711-9d93-857def3f89d0.png">

Protip: with `additionalClasses` you can do magic!

(\* author's estimate, literally no numbers to back it up)

## `InlineNotification`
The layout has been slightly tweaked so the icon is aligned to the top, regardless of total height.

## Icons
**95** (+- a couple) UI icons and 1 block icon have been tweaked and updated, some redrawn totally, all in pursuit for everything to look better 😄 

# New stuff
## Icons
If all those icon updates weren't enough, there's **38** new UI icons, which brings the total number to **380**! 🎉 

There are also 3 new block icons.

## Helpers & mixins
**`getDefaultBreakpointNames`**
As the name says, gives you a list of the manifest breakpoints, fresh off the store!

**`es-v2-gutenberg-button-active-state`** (+ `es-has-v2-gutenberg-button-active-state`)
If you want the new Gutenberg button active style on any button, there's a mixin for that. 

You can also just add the `es-has-v2-gutenberg-button-active-state` class (or `es-has-v2-gutenberg-button-active-state-inside` on an element with multiple buttons inside)

## Utility classes
There was a big optimization of the way utility classes are generated. There should be way less classes now generated (e.g. negative values for colors, ...)

But, to add something back, the spacing system from Tailwind was borrowed so no more _XL 1/2_ sizes! All the legacy sizes are still there, but the new scale is the preferred way to do components.

**Note**: the `1` value was reserved before for just the value `1`, if you need the spacing size `1`, you need to write `1.0`.

Besides that, there are now more utility classes for nested SVG sizings, colors, opacities, font-sizes,  [...]

2022-08-30 06:35 UTC, piqusy approved these changes
Awesome job!

2022-08-30 06:51 UTC, dingo-d commented on scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.js
> +							className={`es-collapsable-component-use-toggle-v2__expander-button es-button-square-32 es-button-icon-24 es-rounded-full ${areChildrenExpanded ? 'es-nested-color-admin-accent' : ''}`}
How come you didn't use `classnames` helper for this?

2022-08-30 07:14 UTC, dingo-d requested changes
This is a huge PR, so I may have not been super detailed when looking at it (otherwise I'd spend an entire day 😅 ).

Just one general remark: I think in a lot of cases you could have used a `classnames` helper to make the class code a bit more readable.

Other than that the additions look amazing 🙂 Love all the UI improvements 👍🏼

2022-08-30 07:14 UTC, dingo-d commented on scripts/components/compact-responsive/compact-responsive.js
> +											className={`es-compact-responsive-inherit-button es-button-no-icon-spacing es-button-icon-24 es-rounded-0.75 es-text-3 es-h-11! es-px-2.5! es-py-0! es-text-align-left es-gap-2 es-line-h-1.
Could be made more readable with `classnames` helper.

2022-08-30 07:14 UTC, dingo-d commented on scripts/components/simple-repeater/docs/story.js
> +
```suggestion
```

2022-08-30 08:07 UTC, goranalkovic-infinum commented on scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.js
> +							className={`es-collapsable-component-use-toggle-v2__expander-button es-button-square-32 es-button-icon-24 es-rounded-full ${areChildrenExpanded ? 'es-nested-color-admin-accent' : ''}`}
Didn't want to import it for just one conditional xD
But I'll add it

2022-08-30 08:21 UTC, dingo-d commented on scripts/components/collapsable-component-use-toggle/collapsable-component-use-toggle.js
> +							className={`es-collapsable-component-use-toggle-v2__expander-button es-button-square-32 es-button-icon-24 es-rounded-full ${areChildrenExpanded ? 'es-nested-color-admin-accent' : ''}`}
Oh, I thought it was added everywhere 🙈

2022-08-30 10:21 UTC, dadadavorin submitted a review, later dismissed
Wow 🤩 Awesome as always!

2022-08-30 12:03 UTC, volfkarlo requested changes
Micro changes and typo checks 😄 
Great job 👏

2022-08-30 12:18 UTC, goranalkovic-infinum commented on scripts/components/visibility-toggle-responsive/docs/story.js
> +			default: 'false'
Simple! Can't have `boolean`s inherited because they can't be `undefined` 😄  Don't ask how I learned that 😄

2022-08-30 13:00 UTC, simun-ivanac submitted a review, later dismissed

2022-08-30 13:34 UTC, goranalkovic-infinum commented on scripts/components/custom-select/custom-select-default-components.js
> +			className: classNames(['es-custom-select-dropdown-icon -es-mr-1.0', props.selectProps.menuIsOpen ? 'is-open' : '']),
Yup, it's correct 😄

2022-08-30 13:35 UTC, iobrado approved these changes

2022-08-31 09:00 UTC, dingo-d approved these changes

2022-09-01 07:15 UTC, simun-ivanac approved these changes

2022-09-01 07:17 UTC, dadadavorin approved these changes

2022-09-01 07:17 UTC, iobrado approved these changes

2022-09-01 07:55 UTC, volfkarlo approved these changes
👏 ☀️

2022-09-01 08:21 UTC, merged