Reusable blocks header/footer and a bit of fixes
infinum/eightshift-frontend-libs pull request #730
Opened 2023-06-06 08:46 UTC by goranalkovic-infinum

Changes:
- removed `menu` component, as it's not needed anymore
- removed `layout-three-columns` as it's not used anywhere anymore
- added `admin-header-footer-picker` component (renders the settings page)
- updated the default theme logo to the new ES DevKit one
- fixed #726 (bug with Repeater)
- totally revamped theme and plugin setups visually
- theme setup is now fully hands-off and automatic (including `init theme`, `npm install`, `theme activate` and setting up reusable header/footer) 🎉

2023-06-07 14:09 UTC, piqusy requested changes
Looking goooooood 👏🏼 
I have two suggestions 😊

2023-06-07 14:09 UTC, piqusy commented on blocks/init/src/Blocks/components/admin-header-footer-picker/admin-header-footer-picker.php
> +			submit_button(__('Save', 'twentythree'));
`twentythree` ?

2023-06-07 14:09 UTC, piqusy commented on setup/create-wp-project/src/basics/command-line.js
> +const initReusableHF = async () => exec('wp boilerplate init header-footer');
I'd suggest more verbose names for variables 😊

2023-06-12 12:53 UTC, iobrado approved these changes

2023-06-12 13:47 UTC, piqusy approved these changes

2023-06-13 06:14 UTC, iruzevic approved these changes

2023-06-13 06:15 UTC, merged